"""empty message

Revision ID: 11047f3d24fd
Revises: 
Create Date: 2021-05-27 18:55:03.596242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11047f3d24fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('c_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comment', 'c_date')
    # ### end Alembic commands ###
