"""empty message

Revision ID: 1544cf8d3253
Revises: e91861195069
Create Date: 2021-05-21 22:39:16.212236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1544cf8d3253'
down_revision = 'e91861195069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'firstName',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'lastName',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'lastName',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'firstName',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
