"""SocialMedias table'i elave olundu.

Revision ID: 2d597110c3de
Revises: 572d6b23bedf
Create Date: 2021-05-12 23:41:10.497938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d597110c3de'
down_revision = '572d6b23bedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_icon', sa.String(length=100), nullable=True),
    sa.Column('social_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_medias')
    # ### end Alembic commands ###
