"""Employees table'i elave olundu.

Revision ID: 2d7b52383036
Revises: 37f7f14beb78
Create Date: 2021-05-15 00:33:18.292622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7b52383036'
down_revision = '37f7f14beb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_image', sa.String(length=100), nullable=True),
    sa.Column('e_fullname', sa.String(length=100), nullable=True),
    sa.Column('e_profession', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
