"""Sales table'i elave olundu.

Revision ID: 37f7f14beb78
Revises: 2d597110c3de
Create Date: 2021-05-14 15:23:38.229220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f7f14beb78'
down_revision = '2d597110c3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_name', sa.String(length=50), nullable=True),
    sa.Column('sales_icon', sa.String(length=50), nullable=True),
    sa.Column('sales_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
