"""PaymentCard table elave olundu.

Revision ID: 572d6b23bedf
Revises: 3f0f81d6620c
Create Date: 2021-05-12 21:52:12.706004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572d6b23bedf'
down_revision = '3f0f81d6620c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_cards')
    # ### end Alembic commands ###
