"""Post table elave olundu

Revision ID: 5cab81a96692
Revises: f8c2d7a6e24b
Create Date: 2021-05-26 21:11:23.324016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cab81a96692'
down_revision = 'f8c2d7a6e24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_image', sa.String(length=100), nullable=False),
    sa.Column('post_title', sa.String(length=50), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Post')
    # ### end Alembic commands ###
