"""empty message

Revision ID: f8c2d7a6e24b
Revises: 0910ee6a2f8a
Create Date: 2021-05-26 17:01:21.486086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c2d7a6e24b'
down_revision = '0910ee6a2f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductImage')
    # ### end Alembic commands ###
